/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package mongoapp;

/**
 *
 * @author nuwan600
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton_main_add = new javax.swing.JButton();
        jButton_main_update = new javax.swing.JButton();
        jButton_mian_Delete = new javax.swing.JButton();
        jButton_main_view = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton_main_add.setText("User Add");
        jButton_main_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_main_addActionPerformed(evt);
            }
        });

        jButton_main_update.setText("User Update");
        jButton_main_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_main_updateActionPerformed(evt);
            }
        });

        jButton_mian_Delete.setText("User Delete");
        jButton_mian_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_mian_DeleteActionPerformed(evt);
            }
        });

        jButton_main_view.setText("User View");
        jButton_main_view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_main_viewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton_mian_Delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_main_add, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton_main_update, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_main_view, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_main_add)
                    .addComponent(jButton_main_update))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_mian_Delete)
                    .addComponent(jButton_main_view))
                .addContainerGap(106, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_main_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_main_addActionPerformed
        // TODO add your handling code here:
        
        AddUser adduser=new AddUser();
        adduser.setVisible(true);
        
    }//GEN-LAST:event_jButton_main_addActionPerformed

    private void jButton_main_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_main_updateActionPerformed
        // TODO add your handling code here:
        
        UpdateUser adduser=new UpdateUser();
        adduser.setVisible(true);
        
    }//GEN-LAST:event_jButton_main_updateActionPerformed

    private void jButton_mian_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_mian_DeleteActionPerformed
        // TODO add your handling code here:
        
        DeleteUser adduser=new DeleteUser();
        adduser.setVisible(true);
        
    }//GEN-LAST:event_jButton_mian_DeleteActionPerformed

    private void jButton_main_viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_main_viewActionPerformed
        // TODO add your handling code here:
        ViewUser user= new ViewUser();
        user.setVisible(true);
    }//GEN-LAST:event_jButton_main_viewActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_main_add;
    private javax.swing.JButton jButton_main_update;
    private javax.swing.JButton jButton_main_view;
    private javax.swing.JButton jButton_mian_Delete;
    // End of variables declaration//GEN-END:variables
}
